Pages/Cancelar.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace commPinPad.Pages
{
	public class CancelarModel : PageModel
    {
        public void OnGet()
        {
        }

        public async Task OnPostCancelarCompra()
        {
            Console.WriteLine("OnPostSolicitarPago");

            string monto = Request.Form["txtMonto"];
            string tipo = Request.Form["txtTipo"];
            string authId = Request.Form["txtCodAuth"];
            string stan = Request.Form["txtStan"];
            string refNum = Request.Form["txtRefNum"];
            string entryMode = Request.Form["txtEntryMode"];
            string tokenES = Request.Form["txtTokenES"];
            string tokenEZ = Request.Form["txtTokenEZ"];
            string tokenE1 = Request.Form["txtTokenE1"];
            string tokenE2 = Request.Form["txtTokenE2"];


            solicitarCancelar(monto, stan, refNum, tipo, authId, entryMode, tokenES, tokenEZ, tokenE1, tokenE2);
        }

        protected void solicitarCancelar(string monto, string stan, string refNum, string tipo, string authId, string entryMode, string tokenES, string tokenEZ, string tokenE1, string tokenE2)
        {
            string mti = "0420";
            string date = Utils.getDate();
            string time = Utils.getTime();

            XtrPost postCancelar = new XtrPost();

            postCancelar.Add("authId", authId);
            postCancelar.Add("mti", mti);
            postCancelar.Add("monto", monto);
            postCancelar.Add("entryMode", entryMode);
            postCancelar.Add("stan", stan);
            postCancelar.Add("refNumber", refNum);
            postCancelar.Add("localDate", date);
            postCancelar.Add("localTime", time);
            postCancelar.Add("cardType", tipo);
            postCancelar.Add("tokenES", tokenES);
            postCancelar.Add("tokenEZ", tokenEZ);
            postCancelar.Add("e1emv", tokenE1);
            postCancelar.Add("e2emv", tokenE2);

            string datosRespCancel = "";

            datosRespCancel = Post.toHostCancel(postCancelar);

        }

        
    }
}

Pages/Compra.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace commPinPad.Pages
{
	public class CompraModel : PageModel
    {
        public void OnGet()
        {
        }

        public async Task OnPostSolicitarPago()
        {
            Console.WriteLine("OnPostSolicitarPago");
            string monto = Request.Form["txtMonto"];
            string transId = Request.Form["txtTransId"];
            string stan = Request.Form["txtStan"];
            string refNum = Request.Form["txtRefNum"];
            string tipo = Request.Form["txtTipo"];
            string dir = Request.Form["txtDir"];
            string subAfId = Request.Form["txtSubAfiliadoId"];

            Pinpad.abrirPuerto();
            Pinpad.solicitarPago(transId, monto, stan, refNum, tipo, dir, subAfId);
            Pinpad.cerrarPuerto();
        }

        
        
        

    }
}

Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace commPinPad.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

Pages/NewKey.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using System.Timers;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace commPinPad.Pages
{
	public class NewKeyModel : PageModel
    {
        public void OnGet()
        {
        }

        public async Task OnPostGeneraLlave()
        {
            //string datosRespCZ10 = "";
            
            string transId = Request.Form["txtTransIdKeyGen"];
            string stan = Request.Form["txtStanKeyGen"];
            string refNum = Request.Form["txtRefNumKeyGen"];
            


            Pinpad.generaLlave(transId, stan, refNum);


        }

        

    }
}

Pages/SearchPan.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace commPinPad.Pages
{
	public class SearchPanModel : PageModel
    {
        

        public void OnGet()
        {
        }

       
      

        public async Task OnPostBuscarPan()
        {
            Console.WriteLine("OnPostBuscarPan");
            string pan = Request.Form["txtpan"];
            string tipo = Request.Form["txtMonto"];
            Console.WriteLine(tipo);
            buscarPan(pan);
        }

        void buscarPan(string pan) {
            buscarCsv(pan);
        }

        void buscarCsv(string pan) {
            string dir = Environment.CurrentDirectory+"/Pages/files/Bin_03072023.csv";
            System.IO.StreamReader archivo = new System.IO.StreamReader(dir);

            string separador = ",";
            string linea;
            archivo.ReadLine();

            string bin = "";
            string producto = "";
            string tipo = "";
            string marca = "";

            while ((linea = archivo.ReadLine()) != null)
            {
                string[] fila = linea.Split(separador);

                bin = fila[0];
                producto = fila[1];
                tipo = fila[2];
                marca = fila[3];
                if(bin == pan) { break; }
            }
            Console.WriteLine(pan);
            Console.WriteLine("bin "+bin+" producto "+ producto + " y tipo "+ tipo);
        }
    }
}

Pages/SendText.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace commPinPad.Pages
{
	public class SendTextModel : PageModel
    {
        public void OnGet()
        {
        }

        public async Task OnPostEnviarTexto()
        {
            Console.WriteLine("OnPostEnviarTexto");
            Pinpad.abrirPuerto();
            string texto = Request.Form["txttexto"];
            enviarTexto(texto);
            Pinpad.cerrarPuerto();
        }

        public void enviarTexto(string texto)
        {
            String txtHexa = Pinpad.comando_textScreen(texto);
            Pinpad.enviarCodigos(txtHexa);
            Console.WriteLine("Texto enviado");
            //return "Texto enviado";
        }


    }
}

Pages/Cancelar.cshtml
@page
@model CancelarModel
@{
}

<form asp-page-handler="CancelarCompra" method="post">



    <label>Monto:</label><br />
    <input type="text" name="txtMonto" id="txtMonto" value="319.00" /><br />

    <label>Credito/Debito:</label><br />
    <input type="radio" for="txtTipo" name="txtTipo" value="credito" checked="checked" />Credito<br />
    <input type="radio" for="txtTipo" name="txtTipo" value="debito" />Debito<br />

    <label>Chip/Contacless:</label><br />
    <input type="radio" for="txtEntryMode" name="txtEntryMode" value="051" checked="checked" />Chip<br />
    <input type="radio" for="txtEntryMode" name="txtEntryMode" value="071" />Contacless<br />

    <label>Cod. de Autorizacion:</label><br />
    <input type="text" name="txtCodAuth" id="txtCodAuth" value="" /><br />

    <label>Stan:</label><br />
    <input type="text" name="txtStan" id="txtStan" value="1001" /><br />

    <label>refNum:</label><br />
    <input type="text" name="txtRefNum" id="txtRefNum" value="10010" /><br />

    <label>TokenE1:</label><br />
    <input type="text" name="txtTokenE1" id="txtTokenE1" value="" /><br />

    <label>TokenE2:</label><br />
    <input type="text" name="txtTokenE2" id="txtTokenE2" value="" /><br />

    <label>TokenES:</label><br />
    <input type="text" name="txtTokenES" id="txtTokenES" value="" /><br />

    <label>TokenEZ:</label><br />
    <input type="text" name="txtTokenEZ" id="txtTokenEZ" value="" /><br />




    <button style="border-color:black;border-width:1px;" class="btn btn-default">Transaccion con tarjeta</button>
</form>

Pages/Compra.cshtml
@page
@model CompraModel
@{
}

<form asp-page-handler="SolicitarPago" method="post">

    <label>Direccion(Calle):</label><br />
    <input type="text" name="txtDir" id="txtDir" value="Patria" /><br />

    <label>Monto:</label><br />
    <input type="text" name="txtMonto" id="txtMonto" value="319.00" /><br />

    <label>Credito/Debito:</label><br />
    <input type="radio" for="txtTipo" name="txtTipo" value="credito" checked="checked" />Credito<br />
    <input type="radio" for="txtTipo" name="txtTipo" value="debito" />Debito<br />

    <label>ID SubAfiliado:</label><br />
    <input type="text" name="txtSubAfiliadoId" id="txtSubAfiliadoId" value="10252" /><br />

    <label>transId:</label><br />
    <input type="text" name="txtTransId" id="txtTransId" value="" /><br />

    <label>Stan:</label><br />
    <input type="text" name="txtStan" id="txtStan" value="1001" /><br />

    <label>refNum:</label><br />
    <input type="text" name="txtRefNum" id="txtRefNum" value="10011" /><br />

    


    <button style="border-color:black;border-width:1px;" class="btn btn-default">Transaccion con tarjeta</button>
</form>

Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}


@functions{
    public string GetHello()
    {
        return "Hello";
    }

    public string abrirPuerto1(string nombrePuerto)
    {
        Model.puertos = "";
        //puertos = Request.Form["slcpuertos"];

        if (Model.hasData)
        {
            var requestFormData = Request.Form;
            Model.puertos = Request.Form["slcpuertos"];
        }


        //CompanyName = "texto";

        return Model.puertos;
    }
}



@section Scripts
{
    <script>
        $(document).ready(function () {

        });

    function RazorFunction() {
        $("button").html('@GetHello()');
    }

        function abrirPuerto() {
            $nombrePuerto = $("#slcpuertos").val();



        }

        function cerrarPuerto() {
            $nombrePuerto = $("#slcpuertos").val();


        }

        function enviarTexto() {
            $nombrePuerto = $("#slcpuertos").val();


        }

    </script>
}

<form asp-page-handler="AbrirPuerto" method="post">
    <button class="btn btn-default">Abrir puerto</button>
</form>

<form asp-page-handler="CerrarPuerto" method="post">
    <button class="btn btn-default">Cerrar puerto</button>
</form>





<form asp-page-handler="RespC53" method="post">
    <button style="border-color:black;border-width:1px;" class="btn btn-default">Leer Resp C53</button>
</form>




<div>
    <!--

      <br />
    <label>Log:</label><br />
    <textarea id="txtLog" value="@Model.txtLog"></textarea>

    <br />
    <label>Recibido:</label><br />
    <textarea id="txtRecibe" value="@Model.txtRecibido"></textarea>

    <br />
    <label>Enviado:</label><br />
    <textarea id="txtSend" value="@Model.txtSendHexa"></textarea>


    -->
    <select name="slcpuertos" id="slcpuertos" asp-items="Model.portList"></select>


</div>

Pages/NewKey.cshtml
@page
@model NewKeyModel
@{
}

<form asp-page-handler="GeneraLlave" method="post">

    <label>transId:</label><br />
    <input type="text" name="txtTransIdKeyGen" id="txtTransIdKeyGen" value="" /><br />

    <label>Stan:</label><br />
    <input type="text" name="txtStanKeyGen" id="txtStanKeyGen" value="9001" /><br />

    <label>refNum:</label><br />
    <input type="text" name="txtRefNumKeyGen" id="txtRefNumKeyGen" value="90010" /><br />

    <button style="border-color:black;border-width:1px;" class="btn btn-default">Inicializar Llaves</button>
</form>

Pages/SearchPan.cshtml
@page
@model SearchPanModel
@{

   
}

<form asp-page-handler="BuscarPan" method="post">
    <input type="text" id="txtpan" name="txtpan" value="" /><br />
    <label>Credito/Debito:</label><br />
    <input type="radio" for="txtMonto" name="txtMonto" value="credito" />Credito<br />
    <input type="radio" for="txtMonto" name="txtMonto" value="debito" />Debito<br />
    <button style="border-color:black;border-width:1px;" class="btn btn-default">Buscar Tarjeta</button>
</form>

Pages/SendText.cshtml
@page
@model SendTextModel
@{
}

<form asp-page-handler="EnviarTexto" method="post">
    <input type="text" id="txttexto" name="txttexto" value="hola mundo" />
    <button style="border-color:black;border-width:1px;" class="btn btn-default">Enviar</button>
</form>